# Form implementation generated from reading ui file '/tmp/calibre-1ya5xdpq/tmppy3wlwdfrobchio/calibre/gui2/config_widget.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(460, 304)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.cookie = QtWidgets.QLineEdit(parent=Form)
        self.cookie.setObjectName("cookie")
        self.gridLayout.addWidget(self.cookie, 10, 1, 1, 1)
        self.username = QtWidgets.QLineEdit(parent=Form)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 2, 1, 1, 1)
        self.separator_2 = QtWidgets.QFrame(parent=Form)
        self.separator_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.separator_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.separator_2.setObjectName("separator_2")
        self.gridLayout.addWidget(self.separator_2, 11, 0, 1, 2)
        self.password = QtWidgets.QLineEdit(parent=Form)
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 3, 1, 1, 1)
        self.password_label = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_label.sizePolicy().hasHeightForWidth())
        self.password_label.setSizePolicy(sizePolicy)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 3, 0, 1, 1)
        self.cookie_label = QtWidgets.QLabel(parent=Form)
        self.cookie_label.setObjectName("cookie_label")
        self.gridLayout.addWidget(self.cookie_label, 10, 0, 1, 1)
        self.tags = QtWidgets.QLineEdit(parent=Form)
        self.tags.setText("")
        self.tags.setObjectName("tags")
        self.gridLayout.addWidget(self.tags, 14, 1, 1, 1)
        self.separator_1 = QtWidgets.QFrame(parent=Form)
        self.separator_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.separator_1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.separator_1.setObjectName("separator_1")
        self.gridLayout.addWidget(self.separator_1, 9, 0, 1, 2)
        self.username_label = QtWidgets.QLabel(parent=Form)
        self.username_label.setObjectName("username_label")
        self.gridLayout.addWidget(self.username_label, 2, 0, 1, 1)
        self.tags_label = QtWidgets.QLabel(parent=Form)
        self.tags_label.setObjectName("tags_label")
        self.gridLayout.addWidget(self.tags_label, 14, 0, 1, 1)
        self.open_external = QtWidgets.QCheckBox(parent=Form)
        self.open_external.setChecked(True)
        self.open_external.setObjectName("open_external")
        self.gridLayout.addWidget(self.open_external, 12, 0, 1, 2)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.login_button = QtWidgets.QPushButton(parent=Form)
        self.login_button.setEnabled(False)
        self.login_button.setObjectName("login_button")
        self.button_layout.addWidget(self.login_button)
        self.logout_button = QtWidgets.QPushButton(parent=Form)
        self.logout_button.setEnabled(True)
        self.logout_button.setObjectName("logout_button")
        self.button_layout.addWidget(self.logout_button)
        self.gridLayout.addLayout(self.button_layout, 5, 1, 1, 1)
        self.login_status = QtWidgets.QLabel(parent=Form)
        self.login_status.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_status.sizePolicy().hasHeightForWidth())
        self.login_status.setSizePolicy(sizePolicy)
        self.login_status.setText("")
        self.login_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.login_status.setObjectName("login_status")
        self.gridLayout.addWidget(self.login_status, 5, 0, 1, 1)

        self.retranslateUi(Form)
        self.login_button.clicked.connect(self.login_status.clear) # type: ignore
        self.logout_button.clicked.connect(self.cookie.clear) # type: ignore
        self.logout_button.clicked.connect(self.username.clear) # type: ignore
        self.logout_button.clicked.connect(self.password.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):

        Form.setWindowTitle(_("Form"))
        self.password_label.setText(_("Password:"))
        self.cookie_label.setText(_("Auth Cookie:"))
        self.username_label.setText(_("Username:"))
        self.tags_label.setText(_("Added tags:"))
        self.open_external.setText(_("Open store in external web browser"))
        self.login_button.setText(_("Log In"))
        self.logout_button.setText(_("Log Out"))
