name: Zip for Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip plugin
        working-directory: calibre-plugin
        run: |
          zip --quiet -r ../"bookshare-plugin-${{ github.ref_name }}.zip" ./* -x "*.ui"

      - name: Release plugin
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bookshare-plugin-${{ github.ref_name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
          generate_release_notes: true
